CREATE DATABASE LAB

USE LAB

CREATE TABLE EVENTS
(
ID INT  PRIMARY KEY IDENTITY,
NAME NVARCHAR(200) NOT NULL,
[DESC] NVARCHAR(200) NOT NULL,
ADRESS NVARCHAR(200) NOT NULL,
STARTDATE DATE NOT NULL,
STARTTIME TIME NOT NULL,
ENDTIME TIME
)

CREATE TABLE SPEAKERS
(
ID INT  PRIMARY KEY IDENTITY,
FULLNAME NVARCHAR(200) NOT NULL,
POSITION NVARCHAR(200) NOT NULL,
COMPANY NVARCHAR(200) NOT NULL,
IMAGEURL NVARCHAR(200) NOT NULL,

)

CREATE TABLE EVENTSSPEAKERS
(
EVENTID INT FOREIGN KEY REFERENCES EVENTS(ID),
SPEAKERID INT FOREIGN KEY REFERENCES SPEAKERS(ID)
)
