CREATE DATABASE SCHOOL

USE SCHOOL

CREATE TABLE  STUDENTS(
ID INT  PRIMARY KEY IDENTITY,
FULLNAME NVARCHAR(200),
GROUPID INT FOREIGN KEY REFERENCES GROUPS(ID)
)
CREATE TABLE  GROUPS(
ID INT  PRIMARY KEY IDENTITY,
STARTDATE  DATETIME2,
GROUPNO NVARCHAR(200)
)
CREATE TABLE  QUIZS(
ID INT  PRIMARY KEY IDENTITY,
QUIZNAME NVARCHAR(200),
KECIRILMETARIXI  DATETIME2
)

CREATE TABLE STUDENTSQUIZ(

STUDENTID INT NOT NULL FOREIGN KEY REFERENCES STUDENTS(ID),
QUIZID INT NOT NULL FOREIGN KEY REFERENCES QUIZS(ID),
POINT TINYINT  
)

INSERT INTO STUDENTS
VALUES
('ELMAR QARAYEV',2),
('ELMAR QARAYEV',1),
('ELMAR QARAYEV',3),
('ELMAR QARAYEV',4)

INSERT INTO QUIZS
VALUES
('AZ DILI','2023-12-02'),
('RIYAZIYYAT','2024-11-02'),
('FIZIKA','2024-12-04'),
('BIOLOGOYA','2023-11-02')

INSERT INTO GROUPS
VALUES
('2023-12-02','PN12'),
('2024-10-12','PWQ2'),
('2023-12-22','PRF12'),
('2023-10-02','PDD2')



INSERT INTO STUDENTSQUIZ
VALUES
(1,2,34),
(2,3,70),
(3,4,87),
(4,1,100)

SELECT *,(SELECT COUNT(*) FROM STUDENTS AS S WHERE S.GROUPID=G.ID ) AS GROUPCOUNT FROM GROUPS AS G

SELECT S.FULLNAME, MAX(POINT) AS MAXPOINT FROM STUDENTSQUIZ AS SQ
JOIN STUDENTS AS S ON  S.ID=SQ.STUDENTID WHERE S.ID=1
GROUP BY S.FULLNAME

SELECT *,(SELECT AVG(POINT) FROM STUDENTSQUIZ AS SQ WHERE SQ.STUDENTID=S.ID) AS AVGPOINT FROM STUDENTS  AS S
SELECT S.*,G.GROUPNO  FROM STUDENTS AS S
JOIN GROUPS AS G ON  G.ID=S.GROUPID

SELECT G.GROUPNO, G.STARTDATE, avg(SQ.POINT) as AVGPOINT FROM GROUPS AS G
JOIN STUDENTS AS  S ON S.GROUPID=G.ID
JOIN STUDENTSQUIZ AS SQ ON SQ.STUDENTID=S.ID
group by G.GROUPNO, G.STARTDATE

SELECT * FROM QUIZS WHERE DATEDIFF(HOUR,KECIRILMETARIXI,GETDATE())<=24

SELECT * FROM QUIZS  AS Q WHERE Q.KECIRILMETARIXI>GETDATE() 

SELECT * FROM QUIZS AS Q WHERE  not  EXISTS(SELECT * FROM STUDENTSQUIZ AS SQ WHERE SQ.QUIZID=Q.ID)

-- BASQA FORMASI

-- HEC BIR QUIZDE ISTIRAK ETMEMIS  TELEBELER
SELECT S.FULLNAME FROM STUDENTS AS S LEFT JOIN STUDENTSQUIZ  AS SQ ON  S.ID=SQ.STUDENTID
WHERE QUIZID IS  NULL


